export const historyDataList = [
  {
    date: '2018.03 ~',
    companyNm: '디케이테크인 a kakao company',
    department: 'UX팀 / 사원',
    job: '서비스/플랫폼 기획, PM, 팀 매니지먼트, iOS 개발',
    turnoverReasons: 'B2B 기반의 플랫폼 서비스를 넘어 서비스 및 플랫폼 기획 이 후의 운영까지 자사 서비스를 담당하고자 이직 희망',
    jobDataList:[
      { catagory: '기획공통', jobDesc: '프로젝트 일정 및 히스토리 관리 (Jira, Confluence)', participationRate: ''},
      { catagory: '기획공통', jobDesc: '요구사항 정리 및 구체화', participationRate: ''},
      { catagory: '기획공통', jobDesc: 'UI / UX 설계', participationRate: ''},
      { catagory: '기획공통', jobDesc: '프로세스 설계', participationRate: ''},
      { catagory: '기획공통', jobDesc: '기술 검토', participationRate: ''},
      { catagory: '기획공통', jobDesc: '시나리오 기획', participationRate: ''},
      { catagory: '기획공통', jobDesc: '팀 매니징', participationRate: ''},
      { catagory: '개발', jobDesc: 'iOS 앱 개발 (MVVM, MVC)', participationRate: ''},
      { catagory: '개발', jobDesc: '산출물 작성 및 히스토리 관리', participationRate: ''},
    ],
    projectDataList:[
      { projectNm: '카카오 프랜즈 샵', projectDesc: '카카오 커머스 프렌즈 샵 상품관리 中 재고관리 프로세스 개선' },
      { projectNm: '휴가시스템', projectDesc: '카카오 공동체 사내 휴가 시스템' },
      { projectNm: 'MLB (Music License Bank)', projectDesc: '멜론 음원 관리 시스템' },
      { projectNm: '자산관리 시스템', projectDesc: '카카오 공동체 사내 자산관리 시스템' },
      { projectNm: '구매 입찰 시스템', projectDesc: '외주 및 내부 구매 관리 시스템 https://pick.kakaocorp.com/' },
      { projectNm: 'I-Connector', projectDesc: '카카오 오픈빌더 시나리오 기획' },
      { projectNm: '카카오 프렌즈 홈킷 가습기', projectDesc: '카카오프렌즈 IOT 기기 앱' },
      { projectNm: '카카오 프렌즈 홈킷 공기청정기', projectDesc: '카카오프렌즈 IOT 기기 앱' },
      { projectNm: '클래스노트 에디터', projectDesc: '클래스노트 앱 에디터 모듈 앱 개발' },
      { projectNm: 'STTS 음성 데모 앱', projectDesc: '엔터프라이즈 음성인식 SDK 활용 데모 앱' },
      { projectNm: '데모 앱 다운로드 페이지', projectDesc: '엔터프라이즈 하 데모 앱 소개 페이지' },
      { projectNm: 'Speech Api 웹 개편', projectDesc: '엔터프라이즈 음성합성/인식 데모 웹 페이지' },
      { projectNm: '모바일 앱 관리 시스템', projectDesc: '사내 배포 용 앱 관리 페이지' },
      { projectNm: '크라우드 소싱 툴 / 운영툴', projectDesc: '다음 꽃 검색 정보 수집 용 앱' },
      { projectNm: '스타일 트랜스퍼', projectDesc: '화풍 합성 기술 적용 데모 앱' },
      { projectNm: 'SR 데모앱', projectDesc: '사진 복원 기능 데모 앱' },
      { projectNm: '주차 관리 앱 / 운영툴', projectDesc: '제주 카카오 주차 관리 시스템' },
      { projectNm: '스몰톡', projectDesc: '카카오 미니 & TTS 기술을 활용 데모 앱' },
    ]
  },
  {
    date: '2017.08 ~ 2018.03',
    companyNm: '싸이월드',
    department: '서비스 기획팀 / 매니저',
    job: '서비스/플랫폼 기획, PM, 서비스 정책 수립',
    turnoverReasons: '경영약화',
    jobDataList:[
      { catagory: '싸이월드', jobDesc: '앱 서비스 프로세스 분석 및 재 설계', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '앱 서비스 리뉴얼 기획', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '사람검색 Flow 개편 및 UX 설계', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '소셜 로그인 통합 계정 연동 기획', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '타임라인 Feed 개편', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '폴더 구조 개편', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '태그 연동 컨텐츠 기획', participationRate: '100'},
      { catagory: '싸이월드', jobDesc: '싸이 간편로그인 (OAuth) 기획', participationRate: '100'},
      { catagory: 'QUE', jobDesc: 'QUE 로그인 프로세스 기획', participationRate: ''},
      { catagory: '공통', jobDesc: '스토어 관리 (구글 플레이스토어, 애플 앱 스토어, One Store)', participationRate: ''},
      { catagory: '공통', jobDesc: '프로젝트 일정 및 히스토리 관리 (Jira, Confluence) ', participationRate: ''},
    ],
    projectDataList:[
      { projectNm: 'QUE', projectDesc: '매순간 주요뉴스를 확인할 수 있도록 10 개의 카드뉴스를 추천해주는 뉴스 큐레이션 앱' },
      { projectNm: '싸이월드', projectDesc: '과거 SK 에서 서비스한 SNS 서비스' },
    ]
  },
  {
    date: '2015.09 ~ 2017.08',
    companyNm: '주식회사 리메인',
    department: '플랫폼 기획팀 / 대리',
    job: '신규사업 기획, 서비스 기획, 모바일 앱 기획, 서비스 정책 수립, iOS 어플리케이션 개발, 백 엔드 개발, 백 오피스 기획, 디자인 기획 및 리소스 제작, DB 설계, 시스템 기획',
    turnoverReasons: '경영약화',
    jobDataList:[
      { catagory: '공통', jobDesc: 'UI / UX 기획 및 디자인', participationRate: ''},
      { catagory: '공통', jobDesc: '백 오피스 기획 및 디자인', participationRate: ''},
      { catagory: '공통', jobDesc: '프로젝트 관리 및 제휴 업체 관리', participationRate: ''},
      { catagory: '공통', jobDesc: '어플리케이션 프로토타입 제작', participationRate: ''},
      { catagory: '공통', jobDesc: 'iOS 앱 개발', participationRate: ''},
      { catagory: '공통', jobDesc: '디자인 리소스 제작', participationRate: ''},
      { catagory: '공통', jobDesc: '안드로이드 앱 개발', participationRate: '50'},
      { catagory: '공통', jobDesc: 'DB 설계', participationRate: ''},
      { catagory: '공통', jobDesc: '스토어 관리 (구글 플레이스토어, 애플 앱 스토어)', participationRate: ''},
      { catagory: '공통', jobDesc: '프로젝트 일정 및 히스토리 관리', participationRate: '-'},
    ],
    projectDataList:[
      { projectNm: '동네로 멤버십 ', projectDesc: '오프라인에서 진행되는 멤버십 서비스를 온라인 서비스로 전환하는 매장 관리 시스템<br>스탬프,포인트,쿠폰 등을 통해 매장 별 자체 멤버십 관리' },
      { projectNm: '투넘버 문자', projectDesc: 'iOS 사용자를 대상으로 각 이동통신사에서 제공하는 듀얼넘버 서비스의 서드파티 앱으로 사용할 수 있는 서비스<br>투넘버로 문자 발송 및 수신에 대해 관리할 수 있는 서브 연락처 앱' },
      { projectNm: '클린누리', projectDesc: 'iOS 사용자를 대상으로 불법 도박 스팸 문자 관리 서비스<br>자체적인 알고리즘을 통해 데이터를 수집 및 필터링하는 시스템<br>출원번호 : 10-2017-0047353<br>실용신안 : 키워드 라벨링의 학습화를 통한 불법/유해 정보에 대한 차단 방법 및 이를 수행하는 장치<br>영문 : METHOD OF BLOCKING ILLEGAL/HARMFUL INFORMATION BY LEARNING KEAWORD LABELING AND AN APPARATUSE PERFORMING THE SAME' },
      { projectNm: '시설물 관리 시스템 ', projectDesc: '건물관리 시 순찰시계(하드웨어 장비) 를 스마트폰으로 대체하며 점검과정을 QR 코드로 저장 및 리포트할 수 있도록 온라인으로 전환<br>하드웨어 장비 이용 대비 70% 비용절감 효과 제공' },
    ]
  },
  {
    date: '2015.01 ~ 2015.09',
    companyNm: '한빛소프트',
    department: '멀티플랫폼 팀 / 사원',
    job: '국내 서비스 컨텐츠 기획, 글로벌 서비스 재화 밸런싱 기획, 아이템 기획, Season2 - 튜토리얼 기획, UI 리뉴얼 기획',
    turnoverReasons: '이직',
    jobDataList:[
      { catagory: 'FC Manager', jobDesc: '신규 컨텐츠 기획', participationRate: '50'},
      { catagory: 'FC Manager', jobDesc: '이벤트 기획', participationRate: '80'},
      { catagory: 'FC Manager Global', jobDesc: '다국어 지원 UI 기획', participationRate: '50'},
      { catagory: 'FC Manager Global', jobDesc: '게임 내 유료 아이템 기획', participationRate: '50'},
      { catagory: 'FC Manager Global', jobDesc: '글로벌 서비스 재화 밸런스 기획', participationRate: '80'},
    ],
    projectDataList:[
      { projectNm: 'FC Manager', projectDesc: '모바일 축구 시뮬레이션 게임' },
      { projectNm: 'FC Manager Global', projectDesc: '글로벌 (일본 제외) 모바일 축구 시뮬레이션 게임' },
    ]
  },
  {
    date: '2014.03 ~ 2014.10',
    companyNm: 'NHN ENTERTAINMENT',
    department: '',
    job: '주요업무 : 모바일 게임 운영, 운영 틀 기획, 컨텐츠 기획, 이벤트 기획, VOC 분석, 유저 응대',
    turnoverReasons: '모바일 사업부 인원 감축',
    jobDataList:[
      { catagory: '', jobDesc: '운영툴 기획', participationRate: '50'},
      { catagory: '', jobDesc: '모바일 게임 (우파루사가, 가디언스톤, 불꽃닌자, 우파루 마운틴, 문질문질 쿠키런) 서비스 운영', participationRate: '-'},
      { catagory: '', jobDesc: 'VOC 취합 및 보고', participationRate: '-'},
      { catagory: '', jobDesc: '신규 컨텐츠 기획', participationRate: '30'},
      { catagory: '', jobDesc: '유사 게임 시장조사', participationRate: '-'},
      { catagory: '', jobDesc: '신규 및 정기 이벤트 기획', participationRate: '-'},
      { catagory: '', jobDesc: '로그 데이터 분석', participationRate: '-'},
      { catagory: '', jobDesc: '커뮤니티 운영정책 수립 및 운영', participationRate: '50'},
    ],
  },
]